name: Access Request
description: Request we add you to this github organization
title: "Access Request for user: "

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this request.

        We need some information in order to give you write access.

        Reminder - you need to be specifically added in order to
          create repos here, but 'read' access is available to
          all github users.

  - type: input
    id: github_username
    attributes:
      label: Github Username
      placeholder: my_username_here
    validations:
      required: false

  - type: markdown
    attributes:
      value: |

        Note - we are all volunteers here, so your request
               might take a little time for it to be processed.

        While you are waiting, please take the time to familiarize
        yourself with the information at
              https://github.com/weewx-contrib/README-FIRST
